const numeros = [
    {'n': 0, 'vendido': false},
    {'n': 1, 'vendido': false},
    {'n': 2, 'vendido': false},
    {'n': 3, 'vendido': false},
    {'n': 4, 'vendido': false},
    {'n': 5, 'vendido': false},
    {'n': 6, 'vendido': false},
    {'n': 7, 'vendido': false},
    {'n': 8, 'vendido': false},
    {'n': 9, 'vendido': false},
    {'n': 10, 'vendido': false},
    {'n': 11, 'vendido': false},
    {'n': 12, 'vendido': true},
    {'n': 13, 'vendido': true},
    {'n': 14, 'vendido': true},
    {'n': 15, 'vendido': false},
    {'n': 16, 'vendido': true},
    {'n': 17, 'vendido': false},
    {'n': 18, 'vendido': false},
    {'n': 19, 'vendido': true},
    {'n': 20, 'vendido': false},
    {'n': 21, 'vendido': true},
    {'n': 22, 'vendido': false},
    {'n': 23, 'vendido': false},
    {'n': 24, 'vendido': false},
    {'n': 25, 'vendido': false},
    {'n': 26, 'vendido': false},
    {'n': 27, 'vendido': false},
    {'n': 28, 'vendido': false},
    {'n': 29, 'vendido': false},
    {'n': 30, 'vendido': false},
    {'n': 31, 'vendido': false},
    {'n': 32, 'vendido': false},
    {'n': 33, 'vendido': true},
    {'n': 34, 'vendido': false},
    {'n': 35, 'vendido': false},
    {'n': 36, 'vendido': false},
    {'n': 37, 'vendido': false},
    {'n': 38, 'vendido': false},
    {'n': 39, 'vendido': false},
    {'n': 40, 'vendido': false},
    {'n': 41, 'vendido': false},
    {'n': 42, 'vendido': true},
    {'n': 43, 'vendido': false},
    {'n': 44, 'vendido': false},
    {'n': 45, 'vendido': false},
    {'n': 46, 'vendido': false},
    {'n': 47, 'vendido': false},
    {'n': 48, 'vendido': false},
    {'n': 49, 'vendido': false},
    {'n': 50, 'vendido': false},
    {'n': 51, 'vendido': false},
    {'n': 52, 'vendido': true},
    {'n': 53, 'vendido': false},
    {'n': 54, 'vendido': false},
    {'n': 55, 'vendido': false},
    {'n': 56, 'vendido': false},
    {'n': 57, 'vendido': false},
    {'n': 58, 'vendido': false},
    {'n': 59, 'vendido': false},
    {'n': 60, 'vendido': false},
    {'n': 61, 'vendido': true},
    {'n': 62, 'vendido': false},
    {'n': 63, 'vendido': false},
    {'n': 64, 'vendido': false},
    {'n': 65, 'vendido': false},
    {'n': 66, 'vendido': false},
    {'n': 67, 'vendido': false},
    {'n': 68, 'vendido': false},
    {'n': 69, 'vendido': false},
    {'n': 70, 'vendido': false},
    {'n': 71, 'vendido': false},
    {'n': 72, 'vendido': false},
    {'n': 73, 'vendido': true},
    {'n': 74, 'vendido': true},
    {'n': 75, 'vendido': false},
    {'n': 76, 'vendido': false},
    {'n': 77, 'vendido': true},
    {'n': 78, 'vendido': false},
    {'n': 79, 'vendido': true},
    {'n': 80, 'vendido': false},
    {'n': 81, 'vendido': false},
    {'n': 82, 'vendido': false},
    {'n': 83, 'vendido': false},
    {'n': 84, 'vendido': false},
    {'n': 85, 'vendido': false},
    {'n': 86, 'vendido': false},
    {'n': 87, 'vendido': false},
    {'n': 88, 'vendido': false},
    {'n': 89, 'vendido': true},
    {'n': 90, 'vendido': false},
    {'n': 91, 'vendido': false},
    {'n': 92, 'vendido': false},
    {'n': 93, 'vendido': false},
    {'n': 94, 'vendido': false},
    {'n': 95, 'vendido': false},
    {'n': 96, 'vendido': false},
    {'n': 97, 'vendido': false},
    {'n': 98, 'vendido': false},
    {'n': 99, 'vendido': false},
];

function listarNumeros(){
    numeros.forEach(numeros => {
        var vendido = numeros.vendido?'disabled':''
        var classCss = numeros.vendido?'btn-secondary':'btn-outline-success';
        $("#numeros").append(`<div class="divNumeros"><button onclick="comprar('${numeros.n}')" type="button" class="btn btn-lg ${classCss} btn-circle" ${vendido}>${numeros.n}</button></div>`);
    })
}

function comprar(numero){    
    var text = `Gostaria de adquirir o número: ${numero}`;
    var url = 'https://api.whatsapp.com/send?phone=5515996500127';
    url += `&text=${text}`;
    window.location.replace(url);
}

$( document ).ready(function() {
    listarNumeros();
});
//git add .;  git commit -m "52";  git push;